### ISSUE TITLE
Bump Equinix Terraform Provider to v2.10.0

### ISSUE THREAD

**Issue by dnoland1** [rancherlabs/terraform-harvester-equinix#100]
Release notes at https://github.com/equinix/terraform-provider-equinix/releases/tag/v2.10.0

**Comment by rajeshkio** [comment]
Will do this after https://github.com/rancherlabs/terraform-harvester-equinix/pull/102 is merged to avoid conflicts

**Comment by rajeshkio** [comment]
We have https://github.com/equinix/terraform-provider-equinix/releases/tag/v2.8.0 released. Should we do that?

**Comment by dnoland1** [comment]
Yes, let's go with latest. I'll update the GH title.

**Comment by dnoland1** [comment]
and now latest is 2.9.0...

**Comment by dnoland1** [comment]
updating issue for 2.10.0
